-- Catppuccin 🐈 --
return {}
-- return {
--   "catppuccin/nvim",
--   name = "catppuccin",
--   priority = 1000,
--   config = function()
--     require("catppuccin").setup({
--       color_overrides = {
--         mocha = {
--           base = "#15191e",
--         },
--       },
--       -- Additional settings can go here
--     })
--     vim.cmd.colorscheme("catppuccin")
--   end,
-- }
